name: "CapRover Deploy"
description: "Setup or cleanup CapRover applications"
author: "etienne-dldc"

inputs:
  command:
    description: 'Action to perform: "setup" or "cleanup"'
    required: true

  caprover-password:
    description: "CapRover admin password"
    required: true

  caprover-server:
    description: "CapRover server URL (e.g., https://caprover.example.com)"
    required: true

  caprover-app-name:
    description: "CapRover application name to setup or cleanup"
    required: true

  enable-ssl:
    description: "Enable SSL for the app (setup command only, default: true)"
    required: false
    default: "true"

  has-persistent-data:
    description: "Mark app as having persistent data (setup command only, default: false)"
    required: false
    default: "false"

  config:
    description: "Additional app configuration as JSON (setup command only). Merges with app definition. Schema: { envVars?: IAppEnvVar[], volumes?: IAppVolume[], ports?: IAppPort[], ... }"
    required: false

outputs:
  app-token:
    description: "The CapRover deploy token for the app (only for setup command)"
    value: ${{ steps.caprover.outputs.app-token }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24"

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: npm install

    - name: Run CapRover action
      id: caprover
      shell: bash
      working-directory: ${{ github.action_path }}
      run: node scripts/index.js
      env:
        COMMAND: ${{ inputs.command }}
        CAPROVER_PASSWORD: ${{ inputs.caprover-password }}
        CAPROVER_SERVER: ${{ inputs.caprover-server }}
        CAPROVER_APP_NAME: ${{ inputs.caprover-app-name }}
        ENABLE_SSL: ${{ inputs.enable-ssl }}
        HAS_PERSISTENT_DATA: ${{ inputs.has-persistent-data }}
        CONFIG: ${{ inputs.config }}

branding:
  icon: "cloud"
  color: "blue"
