name: "CapRover Deploy"
description: "Setup or cleanup CapRover applications"
author: "etienne-dldc"

inputs:
  command:
    description: 'Action to perform: "setup" or "cleanup"'
    required: true

  caprover-password:
    description: "CapRover admin password"
    required: true

  caprover-server:
    description: "CapRover server URL (e.g., https://caprover.example.com)"
    required: true

  app-name:
    description: "CapRover application name to setup or cleanup"
    required: true

  project-name:
    description: "CapRover project name (setup command only). Will be created if it doesn't exist. Will be used when creating new applications."
    required: false

  enable-ssl:
    description: "Enable SSL for the app (setup command only, default: true)"
    required: false
    default: "true"

  has-persistent-data:
    description: "Mark app as having persistent data (setup command only, default: false)"
    required: false
    default: "false"

  app-config:
    description: "Additional app configuration as JSON (setup command only). Has higher priority than `app-config-path`. Schema: { envVars?: IAppEnvVar[], volumes?: IAppVolume[], ports?: IAppPort[], ... }"
    required: false

  app-config-path:
    description: "Path to a JSON file containing app configuration (setup command only). Will be merged with app-config option. app-config option has higher priority. Correctly handles envVars and volumes merging."
    required: false

  cleanup-storage:
    description: "Delete storage volumes when cleaning up the app (cleanup command only, default: true)"
    required: false
    default: "true"

outputs:
  app-token:
    description: "The CapRover deploy token for the app (only for setup command)"
    value: ${{ steps.caprover.outputs.app-token }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "24"

    - name: Run CapRover action
      id: caprover
      shell: bash
      working-directory: ${{ github.action_path }}
      run: node scripts/index.ts
      env:
        COMMAND: ${{ inputs.command }}
        CAPROVER_PASSWORD: ${{ inputs.caprover-password }}
        CAPROVER_SERVER: ${{ inputs.caprover-server }}
        CAPROVER_APP_NAME: ${{ inputs.app-name }}
        PROJECT_NAME: ${{ inputs.project-name }}
        ENABLE_SSL: ${{ inputs.enable-ssl }}
        HAS_PERSISTENT_DATA: ${{ inputs.has-persistent-data }}
        APP_CONFIG: ${{ inputs.app-config }}
        APP_CONFIG_PATH: ${{ inputs.app-config-path }}
        CLEANUP_STORAGE: ${{ inputs.cleanup-storage }}

branding:
  icon: "cloud"
  color: "blue"
